# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  nytaggr:
    image: gchr.io/chaoky/nytaggr:main
    restart: always
    ports:
      - 3000:3000
    environment:
      POSTGRES_PASSWORD: example
      NYT_SECRET: arnt
