version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: owo
      POSTGRES_PASSWORD: uwu

  nytaggr:
    image: ghcr.io/chaoky/nytaggr:latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/owo
      POSTGRES_USER: owo
      POSTGRES_PASSWORD: uwu
      NYT_SECRET: cAHo6M2zhPBMoWBXyLT7i9BCjtTZAGM0
